name: project

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - plotly
  - plotly-notebook
  - pandas
  - scipy
  - jupyter
  - ruff
  - seaborn
  - jupyterlab>=3 
  - ipywidgets>=7.6
  - jupyter-dash
  - pip
  - pip:
    - git+https://gitlab.com/ase/ase.git@master
    - hydra-core==1.3.*
    - directory-tree