# Hydra Configuration File

job:
  prefix: descriptive_name
  calculator: DFTB # vasp, gaussian, dftb
  functional:
  basis_set:
  parametrization: GFN2 # for dftb: GFN1, GFN2
  kpoints: [1,1,1]
  lattice_opt: "no"
  calc_type: sp # opt, sp

paths:
  output_path: /path/to/output/directory/
  db_path: /path/to/db/
  input_db_name: database_name.db