# Hydra Configuration File

job:
  prefix: cellobiose
  calculator: vasp
  functional: PBE
  basis_set:
  parametrization:
  kpoints: [1,1,1]
  calc_type: opt

databases:
  input_db_path: ./db/input_structure_${job.prefix}.db
  opt_db_path: ./db/${job.prefix}_${job.label}.db
