# Hydra Configuration File

job:
  prefix: cellobiose
  calculator: vasp # vasp, gaussian, dftb
  functional: PBE
  basis_set:
  parametrization: # for dftb: GFN1, GFN2
  kpoints: [1,1,1]
  calc_type: opt # opt, sp

databases:
  db_path: /path/to/db/
  input_db_name: database.db
