# Hydra Configuration File

job:
  prefix:
  calculator:                 # DFTB, Gaussian, Vasp
  functional:                 # PBE, RPBE, PBEsol, B3LYP or calculator-specific options
  basis_set:                  # for Gaussian: calculator-specific options
  parametrization:            # for DFTB: "GFN1", "GFN2"
  kpoints:                    # [1,1,1]
  encut:                      # VASP default: 500
  lattice_opt:                # "yes", "no"
  dispersion_correction:      
  calc_type: opt              # "sp", "opt"

paths:
  output_path:                # Default: parent directory to db_path
  db_path: 
  input_db_name: