# Hydra Configuration File

job:
  prefix: cellobiose
  calculator: vasp
  functional: PBE
  basis_set: ""
  parametrization: ""
  kpts: (1,1,1)
  calc_type: opt
  method: ${job.functional}_${job.basis_set}_${job.parametrization}
  label: ${job.calculator}_${job.method}_${job.calc_type}

databases:
  input_db_path: ./db/input_structure_${job.prefix}.db
  opt_db_path: ./db/${job.prefix}_${job.label}.db
